module.exports = {
    common_01: '方法不支持',
    common_api_01: '已经存在',
    common_api_02: '选定项目不存在',
    common_api_03: '文件类型错误',
    api_template_01: '模板不存在',
    domain_01: '组织已存在',
    domain_02: '机构不存在',
    group_01: '用户组已存在',
    group_02: '用户组不存在',
    group_03: '叶子节点没有路径',
    group_04: '用户组下存在用户',
    usersetting_01: '密码错误',
    usersetting_02: '用户不存在',
    operator_01: '组不存在',
    operator_02: '用户已经存在',
    operator_03: '用户不存在',
    operator_04: '用户下有未完成订单',
    customer_01: '客户组不存在',
    customer_02: '客户已经存在',
    customer_03: '客户不存在',
    customer_04: '手机号已存在',
    menu_01: '菜单已经存在',
    menu_02: '菜单不存在',
    menu_03: '菜单下有子项',
    menu_04: '未配置路径',
    mbap_01: 'domain_id is missing',
    reg_01: 'phone is missing',
    reg_02: 'type is missing',
    reg_03: 'code is missing',
    reg_04: 'password is missing',
    reg_05: 'name is missing',
    auth_01: 'domain is missing',
    auth_02: 'username is missing',
    auth_03: 'identifyCode is missing',
    auth_04: 'magicNo is missing',
    auth_05: '用户不存在或密码错误',
    auth_06: '电话不存在',
    auth_07: '类型不存在',
    auth_08: '发送验证码失败',
    auth_09: '验证码错误',
    auth_10: '用户组不存在',
    auth_11: '用户类型不存在',
    auth_12: '验证码错误',
    auth_13: '请输入正确的手机号码',
    auth_14: '请输入正确的用户类型',
    auth_15: 'type is missing',
    auth_16: 'phone is missing',
    auth_17: 'code is missing',
    auth_18: 'password is missing',
    auth_19: 'loginType is missing',
    auth_20: 'wxCode is missing', 
    auth_21: '微信验证失败',
    auth_22: '用户不存在',
    farmerbuywx_01: 'wxCode is missing',
    farmerbuywx_02: 'phone is missing',
    farmerbuywx_03: 'captcha is missing',
    farmerbuywx_04: 'info is missing', 
    farmerbuywx_05: '微信授权失败'
};
